INSERT INTO departments (name, type, head_office_name)
SELECT v.name, 'government', NULL
FROM (
  VALUES
    ('Central Bank of Sri Lanka'),
    ('Ceylon Electricity Board'),
    ('Colombo Municipal Council'),
    ('Colombo Stock Exchange'),
    ('Commission to Investigate Allegations of Bribe'),
    ('Department of Animal Production and Health'),
    ('Department of Archives'),
    ('Department of Buddhist Affairs'),
    ('Department of Commerce'),
    ('Department of Examinations'),
    ('Department of Export Agriculture'),
    ('Department of Fisheries and Aquatic Resources'),
    ('Department of Government Factory'),
    ('Department of Government Printing (Gazzettes)'),
    ('Department of Hindu Affairs'),
    ('Department of Immigration and Emigration'),
    ('Department of Land Settlement'),
    ('Department of Meteorology'),
    ('Department of Motor Traffic'),
    ('Department of National Botanic Gardens'),
    ('Department of Official Languages'),
    ('Department of Public Trustee'),
    ('Department of Railways'),
    ('Department of Samurdhi Development'),
    ('Department of Social Services'),
    ('Department of Technical Education and Training'),
    ('Department of Valuation'),
    ('Department of Wildlife Conservation'),
    ('Disaster Management Centre'),
    ('Epidemiology Unit'),
    ('eProcurement'),
    ('Geological Survey and Mines Bureau'),
    ('Health Promotion Bureau'),
    ('Hector Kobbekaduwa Agrarian Research and Training Institute'),
    ('Information and Communication Technology Agency of Sri Lanka'),
    ('Lanka Electricity Company (Pvt) Ltd'),
    ('Mahaweli Authority of Sri Lanka'),
    ('Ministry of Agriculture'),
    ('Ministry of Child Development and Women`s Affairs'),
    ('Ministry of Culture and Art Affairs'),
    ('Ministry of Defence and Urban Development'),
    ('Ministry of Digital Economy'),
    ('Ministry of Disaster Management'),
    ('Ministry of Education'),
    ('Ministry of Enterprise Development and Investment Promotion'),
    ('Ministry of Finance and Planning'),
    ('Ministry of Fisheries and Aquatic Resource Development'),
    ('Ministry of Foreign Affairs'),
    ('Ministry of Health'),
    ('Ministry of Higher Education'),
    ('Ministry of Highways'),
    ('Ministry of Highways and Road Development – Maga Naguma Division'),
    ('Ministry of Highways, Ports Shipping'),
    ('Ministry of Housing and Common Amenities'),
    ('Ministry of Indigenous Medicine'),
    ('Ministry of Industries'),
    ('Ministry of Irrigation & Water Resources Management'),
    ('Ministry of Justice'),
    ('Ministry of Justice and Law Reforms'),
    ('Ministry of Labour and Labour Relations'),
    ('Ministry of Land and Land Development'),
    ('Ministry of Livestock and Rural Community Development'),
    ('Ministry of Local Government and Provincial Councils'),
    ('Ministry of Mass Media and Information'),
    ('Ministry of Nation Building and State Infrastructure Development'),
    ('Ministry of National Heritage Cultural Affairs'),
    ('Ministry of Parliamentary Affairs'),
    ('Ministry of Petroleum Industries'),
    ('Ministry of Plan Implementation'),
    ('Ministry of Plantation Industries'),
    ('Ministry of Postal Services'),
    ('Ministry of Power and Energy'),
    ('Ministry of Public Administration and Home Affairs'),
    ('Ministry of Public Administration, Home Affairs, Provincial Councils and Local Government'),
    ('Ministry of Religious Affairs and Moral Upliftment'),
    ('Ministry of Resettlement'),
    ('Ministry of Sport'),
    ('Ministry of State Resources and Enterprise Development'),
    ('Ministry of Technology, Research and Atomic Energy'),
    ('Ministry of Textile Industry Development'),
    ('Ministry of Tourism'),
    ('Ministry of Trade, Commerce, Food security and Co-operative Development'),
    ('Ministry of Traditional Industries Small Enterprises Development'),
    ('Ministry of Transport'),
    ('Ministry of Urban Development and Housing – Housing & Construction Division'),
    ('Ministry of Urban Development and Sacred Area Development'),
    ('Ministry of Vocational and Technical Training'),
    ('Ministry of Water Supply and Drainage'),
    ('Ministry of Women, Child Affairs & Social Empowerment'),
    ('Ministry of Youth Affairs Skills Development'),
    ('National Secretariat for Non-governmental Organizations'),
    ('National Water Supply & Drainage Board'),
    ('Public Service Commission'),
    ('Registrar General''s Department'),
    ('Registrar of Companies'),
    ('Road Developemnt Authority'),
    ('Sri Lanka Air force'),
    ('Sri Lanka Army'),
    ('Sri Lanka Ayurvedic Drugs Corporation'),
    ('Sri Lanka Export Development Board'),
    ('Sri Lanka Land Reclamation and Development Corporation'),
    ('Sri Lanka Planetarium'),
    ('Sri Lanka Police'),
    ('Sri Lanka Post'),
    ('Sri Lanka Railways'),
    ('Sri Lanka Standards Institute'),
    ('Sri Lanka Tea Board'),
    ('Sri Lanka Tourism'),
    ('Sri Lanka Tourism Development Authority'),
    ('Survey Department'),
    ('Tea Small Holdings Development Authority'),
    ('Telecommunications Regulatory Commission of Sri Lanka'),
    ('The Parliament'),
    ('Tower Hall Theater Foundation'),
    ('Water Resources Board'),
    ('Welfare Benifits Board')
) AS v(name)
WHERE NOT EXISTS (
  SELECT 1
  FROM departments d
  WHERE lower(d.name) = lower(v.name)
);
