server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${POSTGRES_DB:auth_db}}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:root}}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true

app:
  jwt:
    secret: ${JWT_SECRET:supersecretkey-supersecretkey-supersecretkey-32bytes+}
    expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}

management:
  endpoints:
    web:
      exposure:
        include: health,info
